{{- $fullName := include "bloom.fullname" . -}}
{{- $labels := include "bloom.labels" . }}
{{- $svcPort := .Values.service.port -}}
{{- $kubeversion := .Capabilities.KubeVersion.GitVersion}}
{{ range .Values.bloom.proxy.shards }}
{{- if .ingress.enabled -}}
{{- if and .ingress.className (not (semverCompare ">=1.18-0" $kubeversion)) }}
  {{- if not (hasKey .ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .ingress.annotations "kubernetes.io/ingress.class" .ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" $kubeversion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $kubeversion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-shard-{{ .shard }}
  labels:
    {{$labels | nindent 4 }}

  annotations:
    {{- with .ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers Bloom-Request-Shard {{ .shard }};

spec:
  {{- if and .ingress.className (semverCompare ">=1.18-0" $kubeversion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .ingress.tls }}
  tls:
    {{- range .ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $kubeversion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $kubeversion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}